#5. 
SELECT COUNT(NAME) AS COUNT
FROM STARS
WHERE (SELECT AVG(MASS)
FROM STARS)<=MASS

#6.
SELECT NAME, DENSE_RANK() OVER (ORDER BY SALARY DESC) AS "RANK", SALARY
FROM EMPLOYEES
ORDER BY NAME ASC

